plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pinedaagencygroup.leads'
    compileSdk 35

    defaultConfig {
        applicationId 'com.pinedaagencygroup.leads'
        minSdk 23
        targetSdk 35
        versionCode 9
        versionName '1.8'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-messaging'
}
