plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pimflextv.next'
    compileSdk 35

    defaultConfig {
        applicationId 'com.pimflextv.next'
        minSdk 21
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.4.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
    implementation 'androidx.media3:media3-ui:1.4.1'
    implementation 'org.videolan.android:libvlc-all:3.7.6'
}
